### ISSUE TITLE
Firefox Notes Integration / Synchronization

### ISSUE THREAD

**Issue by heyakyra** [pyluyten/bijiben#38]
Sub-task of #12 (Implement Synchronization) and similar to #35 (Google Keep integration) but for Firefox Notes which would be great to be able to use with a standalone client such as this. 

https://github.com/mozilla/notes

**Comment by pyluyten** [comment]
Hello, GNOME Notes is now hosted on official GNOME repository. So this would be here : https://gitlab.gnome.org/GNOME/gnome-notes

For example you may want to discuss this in https://gitlab.gnome.org/GNOME/gnome-notes/issues/120

**Comment by heyakyra** [comment]
Thanks, I linked there to https://github.com/mozilla/notes/issues/1430#issuecomment-457678649
